// archived/archive/Client/src/components/Budgets.tsx
// import React from 'react'

import BudgetBar from "./Budgetbar";

export default function Budgets() {
  return (
    <>
      <div className="text-center mt-5">
        <h1 className="fw-bold fs-3 mt-5 mb-3">Budgets</h1>
        <div className="d-flex justify-content-center">
          <div
            className="card bg-dark bg-gradient" /*style={{ width: "25rem"}}*/
          >
            {/* Card Header */}
            {/* <div className="card-header">
              Total Balance
            </div> */}

            {/* Card Body */}
            <div className="card-body" style={{ color: "white" }}>
              {/* <h5 className="card-title">Total Balance</h5> */}
              <p className="card-text">
                <BudgetBar category="Groceries" spent={255} budget={400} />
                <BudgetBar category="Rent" spent={1200} budget={1200} />
                <BudgetBar category="Entertainment" spent={400} budget={300} />
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// archived/archive/Old_vueClient/src/components/Budgets.vue
<template>
  <div class="container m-5 p-5">
    <h1 class="fw-bold fs-3 mt-5 mb-3 text-center">
      Budget for {{ currentMonthString }}
    </h1>
    <div class="d-flex justify-content-center">
      <div :class="`card ${isDark ? 'bg-dark' : ''} bg-gradient`">
        <div class="card-body">
          <p class="card-text">
            <Budgetsbar
              v-for="value in budgetInfo"
              :key="value.id"
              :category="value.category"
              :spent="value.spent"
              :budget="value.budget"
              @update:budgetLimit="(newLimit) => updatebudgetLimit(value.id, newLimit)"
            />
            <!-- listen for that change -->
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useTheme } from "../stores/theme-store";
import Budgetsbar from "./Budgetsbar.vue";

const { isDark } = useTheme();

function updatebudgetLimit(id: number, newLimit: number) {
  const item = budgetInfo.value.find((b) => b.id === id);
  if (item) item.budget = newLimit;

  console.log("updated budget limit");
  // TODO: make api call here
}

const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const currentMonthString = monthNames[new Date().getMonth()];

const budgetInfo = ref([
  {
    id: 0,
    category: "Groceries",
    budget: 400,
    spent: 255,
  },
  {
    id: 1,
    category: "Rent",
    budget: 1200,
    spent: 1200,
  },
  {
    id: 2,
    category: "Entertainment",
    budget: 400,
    spent: 300,
  },
]);
</script>

<style scoped>
/* * {
  color: white;
} */
</style>
